### ISSUE TITLE
Support in ROS2

### ISSUE THREAD

**Issue by SteveMacenski** [OpenVSLAM-Community/openvslam_ros#2]
Hi,

I notice only monocular is supported in ROS2 (with ROS1 having all 3). This is something me and my colleague can help commit to implementing as part of the Nav2 / ROS2 integration work. We'll likely have other features / things we want to expose (like adding a feature map publishing topic, among others) but figured this is a good place to get the ball rolling.

**Comment by ymd-stella** [comment]
The current ROS version of openvslam_ros works even before noetic, as long as the dependent OpenCV versions are resolved correctly. Therefore, I will delete the noetic-devel branch and keep the ros branch.

**Comment by SteveMacenski** [comment]
What's the `main` branch in this context?

**Comment by ymd-stella** [comment]
`main` was the default branch.
The `ros2` branch is now the default. (I deleted the `ros2` branch and renamed the `main` branch to `ros2`.)

**Comment by SteveMacenski** [comment]
@AlexeyMerzlyakov please provide a concise, bulleted list of things to do to go from where we are until a full release of a functioning ROS2 integratable openvSLAM system (support rgbd, stereo, ROS timing, parameters, calibration, documentation, testing, CI, release, occ grid, etc) so that we can see explicitly the status of all of the ongoing things / future subtrasks

**Comment by AlexeyMerzlyakov** [comment]
Sure, the scope of current activities is listed below (will be dynamically updating as tasks are completed or appeared):

**Development items**
- [x] Support for Stereo cameras in ROS2 OpenVSLAM [done in https://github.com/OpenVSLAM-Community/openvslam/pull/41]
- [x] Support for RGB-D cameras in ROS2 OpenVSLAM [done in #6]
- [x] Adding "camera_link->map" transform  [in progress in #9]
- [x] Publish Odometry or Pose message for fusion into R_L if fusing with multiple SLAM/localization systems (adding a TF-reader to obtain arbitrary robot geometry conversions to publish pose in "odom" frame) [in progress in #9]
- [x] TF transformation parameterized by publish_tf bool parameterization (default true) [in progress in #9]
- [x] Support for "map->odom" transform [in progress in #9]
- [ ] Cameras calibration analysis and support [in progress, #7]
- [ ] Parameterize topic names / frames [in progress]
- [ ] Localization mode respond to a relocalization request from topic (like AMCL does with initial_pose) [in progress, #11]
- [ ] One node unification driven by ROS2 parameters for SLAM/Localization and different modes [planning, #25]
- [ ] Investigate and extract Occupancy Grid map [paused till all above tasks to be completed]

**Testing**
- [ ] Testing of major features, including Stereo, RGBD, localization in prior map, and timing (make sure we didn't break anything)
- [ ] CPU/memory benchmarking
- [ ] Full-system testing in a reasonable sized environment on a robot and record dataset, localize in sometime later in different lighting conditions as a demo (office building, etc)

**Documentation**
- [ ] Documentation update for OpenVSLAM based on above tasks

**Comment by SteveMacenski** [comment]
- [ ] testing of major features, including Stereo, RGBD, localization in prior map, and timing (make sure we didnt break anything)
- [ ] Publish Odometry or Pose message for fusion into R_L if fusing with multiple SLAM/localization systems
- [ ] TF transformation parameterized by `publish_tf` bool parameterization (default true)
- [ ] CPU/memory benchmarking
- [ ]  Localization mode respond to a relocalization request from topic (like AMCL does with `initial_pose`)
- [ ] parameterize topic names / frames
- [ ] full-system testing in a reasonable sized environment on a robot and record dataset, localize in sometime later in different lighting conditions as a demo (office building, etc)

**Comment by AlexeyMerzlyakov** [comment]
> * testing of major features, including Stereo, RGBD, localization in prior map, and timing (make sure we didnt break anything)
> * TF transformation parameterized by publish_tf bool parameterization (default true)
> * CPU/memory benchmarking
> * parameterize topic names / frames
> * full-system testing in a reasonable sized environment on a robot and record dataset, localize in sometime later in different lighting conditions as a demo (office building, etc)

These items are clear. Agree.

> * Publish Odometry or Pose message for fusion into R_L if fusing with multiple SLAM/localization systems

Could you please give more context on this? Currently, the pose (`nav_msgs::msg::Odometry`) is being published by openvslam-ros in a "camera_link" frame. Did you mean adding a TF-reader to obtain arbitrary robot geometry conversions to publish pose in "odom" frame?

> * Localization mode respond to a relocalization request from topic (like AMCL does with initial_pose)

Should we always re-localize a robot when `initial_pose` messages arrive, or only in the case when tracking is lost?

**Comment by SteveMacenski** [comment]
> Currently, the pose (nav_msgs::msg::Odometry) is being published by openvslam-ros in a "camera_link" frame.

That's fine then, as long as its not removed and the frame of the camera is actually representative of the input topic frame ID. 

> Should we always re-localize a robot when initial_pose messages arrive

Yes, if something comes from that, that's the user, it should be followed.

**Comment by AlexeyMerzlyakov** [comment]
Thanks for noting! Updated https://github.com/OpenVSLAM-Community/openvslam_ros/issues/2#issuecomment-800310426 with items from above.

**Comment by SteveMacenski** [comment]
How fast is the post estimated in openVSLAM (e.g. how often do we update the pose and worth updating the map->odom transform)?

This topic came up in the Nav2 WG meeting - traditionally we update slowly around 1hz or something for lidar slam so we have enough new features to have a real lock on the changes and rely on odometry for local positioning inbetween.

But VSLAM can update much, much faster which begs the question:
- Should we buffer some measurements, filter them, and publish at a reduced rate, which would lag the system a little 
- Or should we publish to TF at the super fast rate, which might cause jitter + reduce odometry smoothness use
